name = "yahya-click-redirect"
main = "worker.js"
compatibility_date = "2024-04-01"
account_id = "fe19d3afc8180ebd5792c34afb1f85af"

# The MEET_URL variable is defined below for deployment.
[vars]
MEET_URL = "https://meet.google.com/buc-xsur-fik"

[[routes]]
pattern = "m.yahya.click"
custom_domain = true

[[routes]]
pattern = "yahya.click/m*"
custom_domain = false

[[routes]]
pattern = "meet.yahya.click"
custom_domain = true

[[routes]]
pattern = "yahya.click/meet*"
custom_domain = false
